### ISSUE TITLE
师傅，我用了你的示例怎么也跑不出来呢？

### ISSUE THREAD

**Issue by Kar1chan** [ek1ng/PhoneHashCrack#1]
请问这个工具还能用不

**Comment by ek1ng** [comment]
可用，可以提供更详细的截图以便解决问题

**Comment by Kar1chan** [comment]
我跑完就是这样的，没有别的显示了。 图好像传不上来，我就复制最后这段给您看看。
[-] start to crack areacode : 173
[-] start to crack areacode : 174
[-] start to crack areacode : 175
[-] start to crack areacode : 176
[-] start to crack areacode : 177
[-] start to crack areacode : 178
[-] start to crack areacode : 180
[-] start to crack areacode : 181
[-] start to crack areacode : 182
[-] start to crack areacode : 183
[-] start to crack areacode : 184
[-] start to crack areacode : 185
[-] start to crack areacode : 186
[-] start to crack areacode : 187
[-] start to crack areacode : 188
[-] start to crack areacode : 189
[-] start to crack areacode : 190
[-] start to crack areacode : 191
[-] start to crack areacode : 192
[-] start to crack areacode : 193
[-] start to crack areacode : 195

[-] start to crack areacode : 196
[-] start to crack areacode : 197
[-] start to crack areacode : 198
3m26.820024209s
[-] start to crack areacode : 199

**Comment by Kar1chan** [comment]
go run main.go --start 11cbd --end 893d3

**Comment by ek1ng** [comment]
非常抱歉，示例有错误，已经更新啦，师傅可以再试一下

**Comment by Kar1chan** [comment]
感谢师傅，确实可以了。师傅我还有问题想要请教下，我这边测试是无法成功的，请问怎么联系师傅比较方便呢？
